apiVersion: v1
kind: Pod
metadata:
  name: docker-build-pod
spec:
  containers:
  - name: maven
    image: maven:3.5.0
    command:
    - cat
    tty: true
  - name: docker
    image: docker:1.11
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  restartPolicy: Never
  volumes:
   - name: docker-sock
     hostPath:
      path: /var/run/docker.sock